/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chanulya Fernando
 */
public class bookdetails extends javax.swing.JFrame {

    /**
     * Creates new form bookdetails
     */
    public bookdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltopic = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbook = new javax.swing.JTable();
        lblbg1 = new javax.swing.JLabel();
        lblbg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(370, 170));
        setName("frmbdetails"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltopic.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltopic.setForeground(new java.awt.Color(0, 102, 153));
        lbltopic.setText("Book Details");
        getContentPane().add(lbltopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 29, -1, -1));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 102, 153));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 397, 90, 37));

        tblbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblbook);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 680, 282));

        lblbg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 700, 240));

        lblbg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            Connection con = DriverManager.getConnection(url, user, pswd);
            
            Statement stmt = con.createStatement();
            
            ResultSet rs1 = stmt.executeQuery("SELECT * FROM book");
            
            DefaultTableModel model1 = new DefaultTableModel();
            model1.setColumnIdentifiers(new String[]{"Book ID", "Book Name", "Author", "Publisher", "Published Year"});
        
            while (rs1.next()) {
                model1.addRow(new Object[]{
                    rs1.getString("bid"),
                    rs1.getString("bname"),
                    rs1.getString("author"),
                    rs1.getString("publisher"),
                    rs1.getString("publishedyear")
                });
            }
            tblbook.setModel(model1);
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ ex.getMessage());
            setVisible(false);
            new returnbook().setVisible(true);
        }
    }//GEN-LAST:event_formComponentShown

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbg1;
    private javax.swing.JLabel lblbg2;
    private javax.swing.JLabel lbltopic;
    private javax.swing.JTable tblbook;
    // End of variables declaration//GEN-END:variables
}
