package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chanulya Fernando
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnewstudent = new javax.swing.JButton();
        btnnewbook = new javax.swing.JButton();
        btnstatistics = new javax.swing.JButton();
        btnissuebook = new javax.swing.JButton();
        btnreturnbook = new javax.swing.JButton();
        btnreports = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        lblstudents = new javax.swing.JButton();
        lblbooks = new javax.swing.JButton();
        lbltopic = new javax.swing.JLabel();
        lblbg1 = new javax.swing.JLabel();
        lblbg2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(176, 216, 253));
        setForeground(new java.awt.Color(137, 223, 246));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setName("frmhome"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1600, 776));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnewstudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnewstudent.setForeground(new java.awt.Color(0, 51, 153));
        btnnewstudent.setText("New Student");
        btnnewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 149, 40));

        btnnewbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnewbook.setForeground(new java.awt.Color(0, 51, 153));
        btnnewbook.setText("New Book");
        btnnewbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 131, 40));

        btnstatistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnstatistics.setForeground(new java.awt.Color(0, 51, 153));
        btnstatistics.setText("Statistics");
        btnstatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatisticsActionPerformed(evt);
            }
        });
        getContentPane().add(btnstatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 122, 40));

        btnissuebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnissuebook.setForeground(new java.awt.Color(0, 51, 153));
        btnissuebook.setText("Issue Book");
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });
        getContentPane().add(btnissuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 135, 40));

        btnreturnbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturnbook.setForeground(new java.awt.Color(0, 51, 153));
        btnreturnbook.setText("Return Book");
        btnreturnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, 147, 40));

        btnreports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreports.setForeground(new java.awt.Color(0, 51, 153));
        btnreports.setText("Reports");
        btnreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 100, 114, 40));

        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(0, 51, 153));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 100, 112, 40));

        lblstudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblstudents.setForeground(new java.awt.Color(0, 51, 153));
        lblstudents.setText("Students");
        lblstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblstudentsActionPerformed(evt);
            }
        });
        getContentPane().add(lblstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 131, 40));

        lblbooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbooks.setForeground(new java.awt.Color(0, 51, 153));
        lblbooks.setText("Books");
        lblbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblbooksActionPerformed(evt);
            }
        });
        getContentPane().add(lblbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 131, 40));

        lbltopic.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltopic.setForeground(new java.awt.Color(0, 51, 153));
        lbltopic.setText("University Library Management System");
        getContentPane().add(lbltopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 670, -1));

        lblbg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg home2.jpg")); // NOI18N
        getContentPane().add(lblbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 780));

        lblbg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg home2.jpg")); // NOI18N
        getContentPane().add(lblbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, 780));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg home2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 400, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewbookActionPerformed
        // TODO add your handling code here:
        new newbook().setVisible(true);
    }//GEN-LAST:event_btnnewbookActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnnewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewstudentActionPerformed
        // TODO add your handling code here:
        new newstudent().setVisible(true);
    }//GEN-LAST:event_btnnewstudentActionPerformed

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        // TODO add your handling code here:
        new issuebook().setVisible(true);
    }//GEN-LAST:event_btnissuebookActionPerformed

    private void btnreturnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbookActionPerformed
        // TODO add your handling code here:
        new returnbook().setVisible(true);
    }//GEN-LAST:event_btnreturnbookActionPerformed

    private void lblstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblstudentsActionPerformed
        // TODO add your handling code here:
        new studentdetails().setVisible(true);
    }//GEN-LAST:event_lblstudentsActionPerformed

    private void lblbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblbooksActionPerformed
        // TODO add your handling code here:
        new bookdetails().setVisible(true);
    }//GEN-LAST:event_lblbooksActionPerformed

    private void btnstatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatisticsActionPerformed
        // TODO add your handling code here:
        new statistics().setVisible(true);
    }//GEN-LAST:event_btnstatisticsActionPerformed

    private void btnreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportsActionPerformed
        // TODO add your handling code here:
        try 
        {
            String reportfile = "C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\LibraryManagementSystem\\src\\librarymanagementsystem\\rptnew.jasper";
            
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(reportfile);
            
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            
            Connection con = DriverManager.getConnection(url, user, pswd);
               
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, con);
            
            JasperViewer.viewReport(jasperPrint, false); 
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
            ex.printStackTrace();
        }
        catch (JRException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error generating report: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnreportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnissuebook;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewbook;
    private javax.swing.JButton btnnewstudent;
    private javax.swing.JButton btnreports;
    private javax.swing.JButton btnreturnbook;
    private javax.swing.JButton btnstatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbg1;
    private javax.swing.JLabel lblbg2;
    private javax.swing.JButton lblbooks;
    private javax.swing.JButton lblstudents;
    private javax.swing.JLabel lbltopic;
    // End of variables declaration//GEN-END:variables
}
