/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Chanulya Fernando
 */
public class issuebook extends javax.swing.JFrame {

    /**
     * Creates new form issuebook
     */
    public issuebook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbid = new javax.swing.JLabel();
        lblstid = new javax.swing.JLabel();
        lblissuedate = new javax.swing.JLabel();
        lblduedate = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtstid = new javax.swing.JTextField();
        dateissue = new com.toedter.calendar.JDateChooser();
        datedue = new com.toedter.calendar.JDateChooser();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        lbltopic = new javax.swing.JLabel();
        lblbg1 = new javax.swing.JLabel();
        lblbg2 = new javax.swing.JLabel();
        lblbg3 = new javax.swing.JLabel();
        lblbg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(370, 170));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblbid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbid.setForeground(new java.awt.Color(0, 102, 153));
        lblbid.setText("Book ID");
        getContentPane().add(lblbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 127, -1, -1));

        lblstid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblstid.setForeground(new java.awt.Color(0, 102, 153));
        lblstid.setText("Student ID");
        getContentPane().add(lblstid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 178, -1, -1));

        lblissuedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblissuedate.setForeground(new java.awt.Color(0, 102, 153));
        lblissuedate.setText("Issued Date");
        getContentPane().add(lblissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 233, -1, -1));

        lblduedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblduedate.setForeground(new java.awt.Color(0, 102, 153));
        lblduedate.setText("Due Date");
        getContentPane().add(lblduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 292, -1, -1));
        getContentPane().add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 127, 211, -1));
        getContentPane().add(txtstid, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 178, 211, -1));
        getContentPane().add(dateissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 231, 211, -1));
        getContentPane().add(datedue, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 290, 211, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 102, 153));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 353, 85, 34));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 102, 153));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 353, 85, 34));

        lbltopic.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltopic.setForeground(new java.awt.Color(0, 102, 153));
        lbltopic.setText("Issue Book");
        getContentPane().add(lbltopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 46, 191, -1));

        lblbg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 360, 230));

        lblbg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 230));

        lblbg3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 360, 230));

        lblbg4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 360, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String bid = txtbid.getText();
        String stid = txtstid.getText();
        String issue = df.format(dateissue.getDate());
        String due = df.format(datedue.getDate());
        String datereturn = "NO";
        
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Class not found!");
                setVisible(false);
                new issuebook().setVisible(true);
            }
            // TODO add your handling code here:
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            
            Connection con = DriverManager.getConnection(url, user, pswd); 
            
            Statement stmt1 = con.createStatement();
            Statement stmt2 = con.createStatement();
            Statement stmt3 = con.createStatement();
            
            ResultSet rsb = stmt1.executeQuery("SELECT * FROM book WHERE bid = '"+bid+"'");
            if(rsb.next())
            {
                ResultSet rss = stmt2.executeQuery("SELECT * FROM student WHERE stid = '"+stid+"'");
                if(rss.next())
                {
                    stmt3.executeUpdate("INSERT INTO issue VALUES('"+bid+"','"+stid+"','"+issue+"','"+due+"','"+datereturn+"')");
                    JOptionPane.showMessageDialog(null,"Book Successfully Issued!");
                    setVisible(false);
                    new issuebook().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid Student ID!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Book ID!");
            }  
            
            rsb.close();
            stmt1.close();
            stmt2.close();
            stmt3.close();
            con.close();
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ ex.getMessage());
            setVisible(false);
            new issuebook().setVisible(true);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private com.toedter.calendar.JDateChooser datedue;
    private com.toedter.calendar.JDateChooser dateissue;
    private javax.swing.JLabel lblbg1;
    private javax.swing.JLabel lblbg2;
    private javax.swing.JLabel lblbg3;
    private javax.swing.JLabel lblbg4;
    private javax.swing.JLabel lblbid;
    private javax.swing.JLabel lblduedate;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lblstid;
    private javax.swing.JLabel lbltopic;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtstid;
    // End of variables declaration//GEN-END:variables
}
