/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Chanulya Fernando
 */
public class returnbook extends javax.swing.JFrame {

    /**
     * Creates new form returnbook
     */
    public returnbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltopic = new javax.swing.JLabel();
        lblbid = new javax.swing.JLabel();
        lblstid = new javax.swing.JLabel();
        lblissue = new javax.swing.JLabel();
        lbldue = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtstid = new javax.swing.JTextField();
        btnreturn = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        txtissue = new javax.swing.JTextField();
        txtdue = new javax.swing.JTextField();
        lblbg1 = new javax.swing.JLabel();
        lblbg2 = new javax.swing.JLabel();
        lblbg3 = new javax.swing.JLabel();
        lblbg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(370, 170));
        setName("frmreturn"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltopic.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltopic.setForeground(new java.awt.Color(0, 102, 153));
        lbltopic.setText("Return Book");
        getContentPane().add(lbltopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 230, -1));

        lblbid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbid.setForeground(new java.awt.Color(0, 102, 153));
        lblbid.setText("Book ID");
        getContentPane().add(lblbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, -1));

        lblstid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblstid.setForeground(new java.awt.Color(0, 102, 153));
        lblstid.setText("Student ID");
        getContentPane().add(lblstid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, -1));

        lblissue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblissue.setForeground(new java.awt.Color(0, 102, 153));
        lblissue.setText("Issue Date");
        getContentPane().add(lblissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, -1));

        lbldue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldue.setForeground(new java.awt.Color(0, 102, 153));
        lbldue.setText("Due Date");
        getContentPane().add(lbldue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, -1));
        getContentPane().add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, -1));
        getContentPane().add(txtstid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, -1));

        btnreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(0, 102, 153));
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 87, 38));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 102, 153));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 87, 38));

        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(0, 102, 153));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 87, 38));
        getContentPane().add(txtissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 210, -1));
        getContentPane().add(txtdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 210, -1));

        lblbg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 350, 230));

        lblbg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 230));

        lblbg3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 230));

        lblbg4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String bid = txtbid.getText();
        String stid = txtstid.getText();
        
        try {
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            Connection con = DriverManager.getConnection(url, user, pswd);
            
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM issue WHERE bid = '"+bid+"' AND stid = '"+stid+"'");
            
            if(rs.next())
            {
                txtissue.setText(rs.getString(3));
                txtdue.setText(rs.getString(4));
                txtbid.setEditable(false);
                txtstid.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Book is not issued to this student!");
                setVisible(false);
                new returnbook().setVisible(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ ex.getMessage());
            setVisible(false);
            new returnbook().setVisible(true);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
        String bid = txtbid.getText();
        String stid = txtstid.getText();
        
        try {
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            Connection con = DriverManager.getConnection(url, user, pswd);
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate("UPDATE issue SET datereturn = 'YES' WHERE bid = '"+bid+"' AND stid = '"+stid+"'");
            JOptionPane.showMessageDialog(null,"Book Returned Successfully!");
            setVisible(false);
            new returnbook().setVisible(true);  
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ ex.getMessage());
            setVisible(false);
            new returnbook().setVisible(true);
        }
    }//GEN-LAST:event_btnreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel lblbg1;
    private javax.swing.JLabel lblbg2;
    private javax.swing.JLabel lblbg3;
    private javax.swing.JLabel lblbg4;
    private javax.swing.JLabel lblbid;
    private javax.swing.JLabel lbldue;
    private javax.swing.JLabel lblissue;
    private javax.swing.JLabel lblstid;
    private javax.swing.JLabel lbltopic;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtdue;
    private javax.swing.JTextField txtissue;
    private javax.swing.JTextField txtstid;
    // End of variables declaration//GEN-END:variables
}
