/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chanulya Fernando
 */
public class statistics extends javax.swing.JFrame {

    /**
     * Creates new form statistics
     */
    public statistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblissuebook = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreturn = new javax.swing.JTable();
        lblreturnbook = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblissue = new javax.swing.JTable();
        btnclose = new javax.swing.JButton();
        lblbg1 = new javax.swing.JLabel();
        lblbg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(370, 170));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblissuebook.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblissuebook.setForeground(new java.awt.Color(0, 102, 153));
        lblissuebook.setText("Issued Book Details");
        getContentPane().add(lblissuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 18, -1, -1));

        tblreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblreturn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 291, 680, 118));

        lblreturnbook.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblreturnbook.setForeground(new java.awt.Color(0, 102, 153));
        lblreturnbook.setText("Returned Book Details");
        getContentPane().add(lblreturnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 225, -1, -1));

        tblissue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblissue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblissue.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblissueComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblissue);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 78, 680, 118));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 102, 153));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 88, 33));

        lblbg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 700, 250));

        lblbg2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chanulya Fernando\\Desktop\\SE\\EAD1\\CW Practice\\Images\\bg color.jpg")); // NOI18N
        getContentPane().add(lblbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void tblissueComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblissueComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblissueComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            String url = "jdbc:mysql://localhost:3306/librarymanagement";
            String user = "root";
            String pswd = "";
            Connection con = DriverManager.getConnection(url, user, pswd);
            
            Statement stmt = con.createStatement();
            
            ResultSet rs1 = stmt.executeQuery("SELECT issue.stid,student.stname,issue.bid,book.bname,issue.issue,issue.due "
                    + "FROM student INNER JOIN book INNER JOIN issue WHERE book.bid = issue.bid AND student.stid = issue.stid "
                    + "AND issue.datereturn = 'NO'");
            //tblissue.setModel(DbUtils.resultSetToTableModel(rs1));
            
            DefaultTableModel model1 = new DefaultTableModel();
            model1.setColumnIdentifiers(new String[]{"Student ID", "Student Name", "Book ID", "Book Name", "Issue Date", "Due Date"});
        
            while (rs1.next()) {
                model1.addRow(new Object[]{
                    rs1.getString("stid"),
                    rs1.getString("stname"),
                    rs1.getString("bid"),
                    rs1.getString("bname"),
                    rs1.getString("issue"),
                    rs1.getString("due")
                });
            }
            tblissue.setModel(model1);
            
            ResultSet rs2 = stmt.executeQuery("SELECT issue.stid,student.stname,issue.bid,book.bname,issue.issue,issue.due "
                    + "FROM student INNER JOIN book INNER JOIN issue WHERE book.bid = issue.bid AND student.stid = issue.stid "
                    + "AND issue.datereturn = 'YES'");
            //tblreturn.setModel(DbUtils.resultSetToTableModel(rs2)); 
            
            DefaultTableModel model2 = new DefaultTableModel();
            model2.setColumnIdentifiers(new String[]{"Student ID", "Student Name", "Book ID", "Book Name", "Issue Date", "Due Date"});
        
            while (rs2.next()) {
                model2.addRow(new Object[]{
                    rs2.getString("stid"),
                    rs2.getString("stname"),
                    rs2.getString("bid"),
                    rs2.getString("bname"),
                    rs2.getString("issue"),
                    rs2.getString("due")
                });
            }
            tblreturn.setModel(model2);
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ ex.getMessage());
            setVisible(false);
            new returnbook().setVisible(true);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblbg1;
    private javax.swing.JLabel lblbg2;
    private javax.swing.JLabel lblissuebook;
    private javax.swing.JLabel lblreturnbook;
    private javax.swing.JTable tblissue;
    private javax.swing.JTable tblreturn;
    // End of variables declaration//GEN-END:variables
}
